version: "3.9"
services:
  mlflow:
    image: neuralsatseg-mlflow
    ports:
      - "5001:6000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow@database:5432/mlflow
      - ARTIFACT_ROOT=/mlruns
    depends_on:
      - database
    networks:
      - neuralsatseg_default
    volumes:
      - mlflow_artifacts:/mlruns
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@database:5432/mlflow
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    networks:
      - neuralsatseg_default

networks:
  neuralsatseg_default:
    driver: bridge

volumes:
  mlflow_artifacts: