version: "3.9"
name: neuralsatseg

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_TRACKING_URI=postgresql://mlflow:mlflow@database:5432/mlflow
      - ARTIFACT_ROOT=/mlruns
    depends_on:
      - database
    networks:
      - neuralsatseg_default
    volumes:
      - ../mlflow_artifacts:/mlruns
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow@database:5432/mlflow
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    ports:
      - "6006:6006"
    networks:
      - neuralsatseg_default
    volumes:
      - ../mlflow_artifacts:/mlruns
    command: >
      tensorboard --logdir /mlruns --host 0.0.0.0 --port 6006

  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    networks:
      - neuralsatseg_default

networks:
  neuralsatseg_default:
    driver: bridge